application: xdrivechallenge2013
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /crossdomain\.xml
  static_files: crossdomain.xml
  upload: crossdomain\.xml

- url: /public
  static_dir: public
  
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: favicon\.ico
  
- url: /.*
  script: GrandCentral.app
  
libraries:
- name: jinja2
  version: latest
 
- name: ssl
  version: latest
  